#!/bin/bash

#40 zeroes, reprsents a nonexistent obj
NULL_COMMIT_ID="0000000000000000000000000000000000000000"
CI_BRANCH="IR_Emerald..*|IR_nonEmerald..*|IR_REPT_2.7_INT..*"
#Minimum interval in seconds between CI triggered events
INTERVAL=10

triggerCI()
{
    lastTriggerTime=0
    currentTime=$(date +%s)
    timeFile="/tmp/ci_time.tmp"
    branch=$(echo $1 | tr [a-z] [A-Z])
    args="--no-check-certificate --auth-no-challenge --http-user=pnw748 --http-password=079ffabb999ca608c05753b7557f442f https://cars.ap.mot-solutions.com:8080/job/PCR-REPT-0-Trigger/buildWithParameters?token=Trigger_Token"
    
    case "$branch" in
        IR_EMERALD?*)
            args+="&IR_BRANCH=${1}&PROJECT_NAME=REPT2.7_Emerald"
            ;;
        IR_NONEMERALD?*)
            args+="&IR_BRANCH=${1}&PROJECT_NAME=REPT2.7_nonEmerald"
            ;;
        IR_REPT_2.7_INT?*)
            args+="&IR_BRANCH=${1}&PROJECT_NAME=REPT2.7"
            ;;
        *)
            return 1
            ;;
    esac
    args+="&SUBMITTER=$2"
    [ -e "$timeFile" ] && read lastTriggerTime < "$timeFile"
    [ "$((lastTriggerTime+INTERVAL))" -gt "$currentTime" ] && sleep $((lastTriggerTime+INTERVAL-currentTime)) &>/dev/null
    wget $args &>/dev/null
    rm -rf buildWithParameters\?token=Trigger_Token* &>/dev/null
    echo $currentTime > $timeFile

    return 0
}

while read oldref newref refname
do
    logger "[post-receive]push event: $oldref $newref $refname"
    [ "$newref" = "$NULL_COMMIT_ID" ] && continue
    if [ -n "$(echo "$refname" | egrep -iw "refs/heads/$CI_BRANCH")" ]
    then
        branch=$(echo "$refname" | cut -d '/' -f 3)
        submitter=$(git --no-pager show -s --format='%an' $newref)
        logger "[post-receive]trigger CI: branch=$branch submitter=$submitter"
        triggerCI "$branch" "$submitter"
    fi
done
